# Generated by Django 4.0 on 2021-12-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
