# Generated by Django 4.0 on 2021-12-15 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0003_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcartitem',
            old_name='name',
            new_name='item',
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mart.product'),
            preserve_default=False,
        ),
    ]
