# Generated by Django 4.0 on 2021-12-15 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0004_rename_name_shoppingcartitem_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcartitem',
            old_name='item',
            new_name='quantity',
        ),
    ]
