# Generated by Django 4.0 on 2021-12-15 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0005_rename_item_shoppingcartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartitem',
            name='shopping_cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mart.shoppingcart'),
            preserve_default=False,
        ),
    ]
