# Generated by Django 3.2.4 on 2021-06-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student', models.IntegerField()),
                ('teacher', models.IntegerField()),
                ('total_staff', models.IntegerField()),
            ],
        ),
    ]
